import json
import requests

# path you want to request
path = "user/repos"

# github username
url = "https://api.github.com/{}"

# if the token is expired, you can generate another one here:
# https://github.com/settings/tokens
token = "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"

headers = {
    "authorization":
        f"Bearer {token}"
}
# insert parameters here
data = {
    # reference: https://docs.github.com/pt/rest/reference/repos#create-a-repository-for-the-authenticated-user
    "name": "github_api_demo",
    "description": "Generated by API"
}

# post request with header and data
response = requests.post(url.format(path), headers=headers, json=data)

# load json
output = json.loads(response.text)
print(output)
